/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.utilities.*;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    private final Console console = new Console();
    @Test void someLibraryMethodReturnsTrue() {

        console.log(Console.Color.CYAN, "This is console log!");
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
