/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish` // need this to publish this as a library. enables command: ./gradlew publish
}
publishing { // need this for jitpack.io to sucessfully build this repo, and it's artifacts
    publications {
        create<MavenPublication>("mavenJava") {
            from(components["java"])
            groupId = "com.github.i-api"
            artifactId = "Console"
            version = "1.0.10"
        }
    }
}

repositories {
    mavenCentral()                              // Use Maven Central for resolving dependencies.
    maven { url = uri("https://jitpack.io") }   // jitpack, allows github repos to be used as maven java dependencies. Not necessary in this "publish/export/provider/dependency repo". Keeping it here just because it allows access to a wide range of packages. It is used by the "importer/consumer/user repo", which ever repo you want to import dependencies into.
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)

    // CUSTOM EDITS:
    implementation("org.json:json:20230618")
    implementation("com.google.code.gson:gson:2.10.1") // https://mvnrepository.com/artifact/com.google.code.gson/gson
    implementation("software.amazon.awssdk:sqs:2.20.98")
    implementation("software.amazon.awssdk:dynamodb:2.20.98")
    implementation("software.amazon.awssdk:regions:2.20.98")
    implementation("software.amazon.awssdk:auth:2.20.98")

    implementation("com.github.spotbugs:spotbugs-annotations:4.8.6") // https://mvnrepository.com/artifact/com.github.spotbugs/spotbugs-annotations

    // Logging
    implementation("org.slf4j:slf4j-api:2.0.0")                     // https://mvnrepository.com/artifact/org.slf4j/slf4j-api
    implementation("ch.qos.logback:logback-classic:1.5.6")          // https://mvnrepository.com/artifact/ch.qos.logback/logback-classic
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
    testLogging.showStandardStreams = true  // gets logging to actually work 😮‍💨😮💀
}
