/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;


import org.example.utilities.Console;
import org.example.utilities.LoadEnv;
class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
        org.example.utilities.Console console = new Console();
        console.log(Console.Color.PURPLE, "someMethod(): This is console.log!");
        final java.util.HashMap credentials = LoadEnv.fromFilePath("example_env.txt"); // env belongs in <Package>/src or <Package>/lib of gradle folder
        System.out.println("accessKeyId: " + credentials.get("accessKeyId"));
        System.out.println("secretAccessKey: " + credentials.get("secretAccessKey"));
    }
}
